### ISSUE TITLE
Overlapping shapes in the nesting output

### ISSUE THREAD

**Issue by misan** [exacloud/Nest4J#6]
Hi, I was testing your very interesting work with a sample case. The following file contains all the polygons, each one in a different line (skip the first too lines though).
[Shapes.txt](https://github.com/exacloud/Nest4J/files/2592032/Shapes.txt)

And the output I get contains several instances of overlapping polygons. 
![image](https://user-images.githubusercontent.com/466120/48663557-2a43a080-ea92-11e8-8a72-a105e5fd346f.png)
Even some polygons are reaching outside of the rectangular bin. The full output as zipped SVG is below. 
[output.svg.zip](https://github.com/exacloud/Nest4J/files/2592035/output.svg.zip)

Previous test with a single bin worked ok. The relevant code setting up the nesting for this example is pasted below:

```java
  NestPath binPolygon = new NestPath();
  double width = 2000;
  double height = 1200;
  binPolygon.add(0, 0);
  binPolygon.add(0, height);
  binPolygon.add(width, height);
  binPolygon.add(width, 0);
  int i=0;
  List<NestPath> list = new ArrayList<NestPath>();
  for (Vector<PVector> out : shapes) {
    NestPath s = new NestPath();
    for (PVector p : out) s.add(p.x, p.y);
    s.bid=i++; 
    list.add(s); 
  }
  Config config = new Config();
  config.USE_HOLE = true;
  Nest nest = new Nest(binPolygon, list, config, 1);
  List<List<Placement>> appliedPlacement = nest.startNest();

```
The only thing that I suspect is that though I set USE_HOLE to true, I failed to provide parts with holes. Not sure if that could trigger this result... ?

**Comment by Yisaer** [comment]
Hi,I notice that you used Vector to build NestPath so I guess you build the param polygons in a wrong way.

The folloing code to build binPolygon not only describe binPolygon's shape as 2000\*1200 rect but also define a rect with 4 Points in a rect coordiates as
(0,0) (2000,0) (2000,1200) (0,1200)

```java 
 NestPath binPolygon = new NestPath();
  double width = 2000;
  double height = 1200;
  binPolygon.add(0, 0);
  binPolygon.add(0, height);
  binPolygon.add(width, height);
  binPolygon.add(width, 0);
  ```

So you have to make sure every 2 Polygon won't be overlapped in this rect Coordinates first including binPolygon before Nest Calculate.

For example , if you want to apply two 20\*10 rect polygons in a 30\*30 rect binPolygon. You should build them in following method.

```java 
NestPath binPolygon = new NestPath();
double width = 30;
double height = 30;
binPolygon.add(0, 0);
binPolygon.add(0, height);
binPolygon.add(width, height);
binPolygon.add(width, 0);

NestPath rect1 = new NestPath();
rect1.add(40,0);
rect1.add(60,0);
rect1.add(60,10);
rect1.add(40,10);

NestPath rect1 = new NestPath();
rect1.add(0,40);
rect1.add(20,40);
rect1.add(20,50);
rect1.add(0,50);

List<NestPath> list = new ArrayList<NestPath>();
list.add(rect1);
list.add(rest2);
```

I guess the the overlapping in your result may caused by your param polygons.

**Comment by misan** [comment]
@Yisaer I got it. 

I made sure polygons did not overlap each other but I made no effort with binPolygon, so for sure some parts may overlap it. 

Sorry, I did not get that detail from reading the documentation. 

I will correct that, try again and report back (it takes about 2 hours of computing time in my computer).

**Comment by misan** [comment]
@Yisaer I have reviewed my polygons and some of them were, in fact, overlapping (my mistake).
